version: '3.9'
services:
  postgres:
    image: postgres:13.1-alpine
    restart: always
    volumes:
      - ../../data/postgres:/var/lib/postgresql/data
      - ../../data/dump:/db-dump
    networks:
      - docker-practice-net
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=school
      - POSTGRES_DB=school

  redis:
    image: redis:6.0.9-alpine
    volumes:
      - ../../data/redis:/var/lib/redis/data
    networks:
      - docker-practice-net
    ports:
      - 6379:6379

networks:
  docker-practice-net: